import {
  HAKONIWA_PROXY_PORT,
  HAKONIWA_PROXY_PROTOCOL,
  HAKONIWA_PROXY_DIR,
  HAKONIWA_BASE_DIR,
  HAKONIWA_AUTH_DIR,
  HAKONIWA_SECRETS_DIR,
  HAKONIWA_CYPRESS_DIR,
  HAKONIWA_CYPRESS_WEBPACK_CONFIG_PATH,
  HAKONIWA_CYPRESS_TSCONFIG_PATH,
  HAKONIWA_CYPRESS_PLUGINS_PATH,
  HAKONIWA_PROXY_HOST,
  HAKONIWA_PROXY_IDENTIFIER,
  HAKONIWA_DAEMON_PROXY_IDENTIFIER,
  HAKONIWA_DAEMON_PROXY_PORT,
  HAKONIWA_DAEMON_PROXY_RULE_NAME,
  HAKONIWA_CYPRESS_UNLIMIT_TIMEOUT,
} from '../../../constants/constants.browser';

const env = Object.assign({
  HAKONIWA_PROXY_PORT,
  HAKONIWA_PROXY_PROTOCOL,
  HAKONIWA_PROXY_DIR,
  HAKONIWA_BASE_DIR,
  HAKONIWA_AUTH_DIR,
  HAKONIWA_SECRETS_DIR,
  HAKONIWA_CYPRESS_DIR,
  HAKONIWA_CYPRESS_WEBPACK_CONFIG_PATH,
  HAKONIWA_CYPRESS_TSCONFIG_PATH,
  HAKONIWA_CYPRESS_PLUGINS_PATH,
  HAKONIWA_PROXY_HOST,
  HAKONIWA_PROXY_IDENTIFIER,
  HAKONIWA_DAEMON_PROXY_IDENTIFIER,
  HAKONIWA_DAEMON_PROXY_PORT,
  HAKONIWA_DAEMON_PROXY_RULE_NAME,
  HAKONIWA_CYPRESS_UNLIMIT_TIMEOUT,
}, Cypress.config('env'));

Cypress.config('env', env);